### ISSUE TITLE
why MAX_ASSEMBLY_LENGTH = 1025024 ？

### ISSUE THREAD

**Issue by Explorer1092** [lesnuages/go-execute-assembly#1]

**Comment by lesnuages** [comment]
@Explorer1092 right now this is arbitrary. I'm relying on the `HostingDLLx64.dll` to do the job of hosting the CLR, fetching the assembly and its arguments, and then load it and execute the entrypoint.

As you can see below, this is a limitation in the DLL code itself, that could be increased if you rebuild your own version:
https://github.com/b4rtik/metasploit-execute-assembly/blob/cc2b1c215e110e79f1ffce37872c102435db7fda/HostingCLR_inject/HostingCLR/HostingCLR.cpp#L11

By the way, a more detailed question in the comment part would have been appreciated.
